/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.vehicleapp;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import uni.views.FBuscar;
import uni.views.DCrear;
import uni.panels.Buscar;
import uni.controls.BuscarControl;

/**
 *
 * @author gabri
 */
public class VehicleApp extends javax.swing.JFrame {
    private DCrear crear;
    private FBuscar buscar;

    /**
     * Creates new form VehicleApp
     */
    public VehicleApp() {
        initComponents(); //dimension de la ventana [63, 23]
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        mItemNuevo = new javax.swing.JMenuItem();
        mItemVer = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vehicle App");
        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        menuOpciones.setText("Opciones");

        mItemNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\workspace\\VehicleApp\\src\\main\\java\\uni\\images\\plus.png")); // NOI18N
        mItemNuevo.setText("Nuevo");
        mItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemNuevoActionPerformed(evt);
            }
        });
        menuOpciones.add(mItemNuevo);

        mItemVer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mItemVer.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\workspace\\VehicleApp\\src\\main\\java\\uni\\images\\view.png")); // NOI18N
        mItemVer.setText("Ver todos");
        mItemVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemVerActionPerformed(evt);
            }
        });
        menuOpciones.add(mItemVer);
        menuOpciones.add(jSeparator2);

        mItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\workspace\\VehicleApp\\src\\main\\java\\uni\\images\\exit.png")); // NOI18N
        mItemSalir.setText("Salir");
        menuOpciones.add(mItemSalir);

        jMenuBar1.add(menuOpciones);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(771, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemNuevoActionPerformed
        crear = new DCrear(this, true);
        crear.setVisible(true);
    }//GEN-LAST:event_mItemNuevoActionPerformed

    private void mItemVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemVerActionPerformed
        desktop.removeAll();
        buscar = new FBuscar();
        desktop.add(buscar);
        buscar.setVisible(true);
        
        validate();
        repaint();
    }//GEN-LAST:event_mItemVerActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            estiloWindows();
            new VehicleApp().setVisible(true);
        });
    }
    
    private static void estiloWindows() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VehicleApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mItemNuevo;
    private javax.swing.JMenuItem mItemSalir;
    private javax.swing.JMenuItem mItemVer;
    private javax.swing.JMenu menuOpciones;
    // End of variables declaration//GEN-END:variables
}
