/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.vehicleapp;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import uni.panels.Crear;
import uni.controls.CrearControl;
import uni.panels.Buscar;
import uni.controls.BuscarControl;

/**
 *
 * @author gabri
 */
public class VehicleApp extends javax.swing.JFrame {
    
    private Crear crear;
    private CrearControl crearControl;
    private Buscar buscar;
    private BuscarControl buscarControl;

    /**
     * Creates new form VehicleApp
     */
    public VehicleApp() {
        initComponents(); //dimension de la ventana [63, 23]
        if (panelBienvenida.isVisible()) {
            botonAtras.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBotones = new javax.swing.JPanel();
        botonAtras = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        panelBienvenida = new javax.swing.JPanel();
        labelCrear = new javax.swing.JLabel();
        labelLeerTodos = new javax.swing.JLabel();
        labelActualizar = new javax.swing.JLabel();
        labelEliminar = new javax.swing.JLabel();
        botonCrear = new javax.swing.JButton();
        botonLeerTodos = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vehicle App");

        panelBotones.setBackground(new java.awt.Color(93, 193, 185));
        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        botonAtras.setBackground(new java.awt.Color(255, 255, 255));
        botonAtras.setText("Atrás");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        panelBotones.add(botonAtras);

        botonSalir.setBackground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panelBotones.add(botonSalir);

        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_END);

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelBienvenida.setBackground(new java.awt.Color(255, 105, 97));
        panelBienvenida.setLayout(new java.awt.GridBagLayout());

        labelCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCrear.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marat Meitchouk\\Documents\\SemestreIII\\ProgramacionII\\VehicleApp\\VehicleApp\\src\\main\\java\\uni\\images\\new.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panelBienvenida.add(labelCrear, gridBagConstraints);

        labelLeerTodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLeerTodos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marat Meitchouk\\Documents\\SemestreIII\\ProgramacionII\\VehicleApp\\VehicleApp\\src\\main\\java\\uni\\images\\search.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panelBienvenida.add(labelLeerTodos, gridBagConstraints);

        labelActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelActualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marat Meitchouk\\Documents\\SemestreIII\\ProgramacionII\\VehicleApp\\VehicleApp\\src\\main\\java\\uni\\images\\updated.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panelBienvenida.add(labelActualizar, gridBagConstraints);

        labelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marat Meitchouk\\Documents\\SemestreIII\\ProgramacionII\\VehicleApp\\VehicleApp\\src\\main\\java\\uni\\images\\recycle-bin.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panelBienvenida.add(labelEliminar, gridBagConstraints);

        botonCrear.setBackground(new java.awt.Color(255, 255, 255));
        botonCrear.setText("Nuevo");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panelBienvenida.add(botonCrear, gridBagConstraints);

        botonLeerTodos.setBackground(new java.awt.Color(255, 255, 255));
        botonLeerTodos.setText("Leer todos");
        botonLeerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLeerTodosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panelBienvenida.add(botonLeerTodos, gridBagConstraints);

        botonActualizar.setBackground(new java.awt.Color(255, 255, 255));
        botonActualizar.setText("Actualizar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panelBienvenida.add(botonActualizar, gridBagConstraints);

        botonEliminar.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("Eliminar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        panelBienvenida.add(botonEliminar, gridBagConstraints);

        panelPrincipal.add(panelBienvenida, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(579, 344));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        panelPrincipal.removeAll();
        if (crear == null) {
            crear = new Crear(); //dimension de la ventana [7, 20]
            crearControl = new CrearControl(crear);
        }
        panelPrincipal.add(crear, BorderLayout.CENTER);
        botonAtras.setEnabled(true);
        validate();
        repaint();
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        panelPrincipal.removeAll();
        resetPaneles();
        panelPrincipal.add(panelBienvenida, BorderLayout.CENTER);
        botonAtras.setEnabled(false);
        validate();
        repaint();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonLeerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLeerTodosActionPerformed
        panelPrincipal.removeAll();
        if (buscar == null) {
            buscar = new Buscar();
            buscarControl = new BuscarControl(buscar);
        }
        panelPrincipal.add(buscar, BorderLayout.CENTER);
        botonAtras.setEnabled(true);
        validate();
        repaint();
    }//GEN-LAST:event_botonLeerTodosActionPerformed

    private void resetPaneles() {
        crear = null;
        buscar = null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            estiloWindows();
            new VehicleApp().setVisible(true);
        });
    }
    
    private static void estiloWindows() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VehicleApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonLeerTodos;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel labelActualizar;
    private javax.swing.JLabel labelCrear;
    private javax.swing.JLabel labelEliminar;
    private javax.swing.JLabel labelLeerTodos;
    private javax.swing.JPanel panelBienvenida;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
