/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.views;

import java.awt.BorderLayout;
import uni.panels.Buscar;
import uni.controls.BuscarControl;

/**
 *
 * @author Sistemas-11
 */
public class FBuscar extends javax.swing.JInternalFrame {
    
    private Buscar buscar;
    private BuscarControl buscarControl;

    /**
     * Creates new form FBuscar
     */
    public FBuscar() {
        initComponents();
        bienvenida();
    }
    
    private void bienvenida() {
        panelPrincipal.removeAll();
        if (buscar == null) {
            buscar = new Buscar();
            buscarControl = new BuscarControl(buscar);
        }
        panelPrincipal.add(buscar, BorderLayout.CENTER);
        validate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Todos los vehículos");

        panelPrincipal.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(396, 296));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
