/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.views;

import java.awt.BorderLayout;
import uni.panels.Crear;
import uni.controls.CrearControl;

/**
 *
 * @author Sistemas-11
 */
public class FCrear extends javax.swing.JInternalFrame {
    
    private Crear crear;
    private CrearControl crearControl;

    /**
     * Creates new form FCrear
     */
    public FCrear() {
        initComponents();
        bienvenida();
    }
    
    private void bienvenida() {
        panelPrincipal.removeAll();
        if (crear == null) {
            crear = new Crear();
            crearControl = new CrearControl(crear);
        }
        panelPrincipal.setSize(crear.getSize());
        panelPrincipal.add(crear, BorderLayout.CENTER);
        validate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();

        setClosable(true);
        setResizable(true);
        setTitle("Crear Vehículo");

        panelPrincipal.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 650, 366);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
