/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.panels;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author gabri
 */
public class Bienvenida extends javax.swing.JPanel {

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
    }

    public JButton getBotonActualizar() {
        return botonActualizar;
    }

    public JButton getBotonCrear() {
        return botonCrear;
    }

    public JButton getBotonEliminar() {
        return botonEliminar;
    }

    public JButton getBotonLeerTodos() {
        return botonLeerTodos;
    }

    public JLabel getLabelActualizar() {
        return labelActualizar;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelCrear = new javax.swing.JLabel();
        botonCrear = new javax.swing.JButton();
        labelLeerTodos = new javax.swing.JLabel();
        botonLeerTodos = new javax.swing.JButton();
        labelActualizar = new javax.swing.JLabel();
        botonActualizar = new javax.swing.JButton();
        labelEliminar = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(75, 0, 130));
        setLayout(new java.awt.GridBagLayout());

        labelCrear.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\workspace\\VehicleApp\\src\\main\\java\\uni\\images\\new.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 7);
        add(labelCrear, gridBagConstraints);

        botonCrear.setText("Crear");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 7);
        add(botonCrear, gridBagConstraints);

        labelLeerTodos.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\workspace\\VehicleApp\\src\\main\\java\\uni\\images\\search.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 7);
        add(labelLeerTodos, gridBagConstraints);

        botonLeerTodos.setText("Todos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 7);
        add(botonLeerTodos, gridBagConstraints);

        labelActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelActualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\workspace\\VehicleApp\\src\\main\\java\\uni\\images\\updated.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 7);
        add(labelActualizar, gridBagConstraints);

        botonActualizar.setText("Actualizar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 7);
        add(botonActualizar, gridBagConstraints);

        labelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\workspace\\VehicleApp\\src\\main\\java\\uni\\images\\recycle-bin.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 7);
        add(labelEliminar, gridBagConstraints);

        botonEliminar.setText("Eliminar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 7);
        add(botonEliminar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonLeerTodos;
    private javax.swing.JLabel labelActualizar;
    private javax.swing.JLabel labelCrear;
    private javax.swing.JLabel labelEliminar;
    private javax.swing.JLabel labelLeerTodos;
    // End of variables declaration//GEN-END:variables
}
