/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.panels;

import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author gabri
 */
public class Buscar extends javax.swing.JPanel {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
    }

    public JTextField getFieldBuscar() {
        return fieldBuscar;
    }

    public JTable getTablaVehiculos() {
        return tablaVehiculos;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCuadroBusqueda = new javax.swing.JPanel();
        labelBuscar = new javax.swing.JLabel();
        fieldBuscar = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        contendorTabla = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        panelCuadroBusqueda.setBackground(new java.awt.Color(253, 253, 150));
        panelCuadroBusqueda.setLayout(new java.awt.GridBagLayout());

        labelBuscar.setText("Buscar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 4, 4);
        panelCuadroBusqueda.add(labelBuscar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 4, 3);
        panelCuadroBusqueda.add(fieldBuscar, gridBagConstraints);

        labelTitulo.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Vehículos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        panelCuadroBusqueda.add(labelTitulo, gridBagConstraints);

        add(panelCuadroBusqueda, java.awt.BorderLayout.PAGE_START);

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaVehiculos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaVehiculos.setEnabled(false);
        contendorTabla.setViewportView(tablaVehiculos);

        add(contendorTabla, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane contendorTabla;
    private javax.swing.JTextField fieldBuscar;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelCuadroBusqueda;
    private javax.swing.JTable tablaVehiculos;
    // End of variables declaration//GEN-END:variables
}
