/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.panels;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author gabri
 */
public class Crear extends javax.swing.JPanel {

    
    
    public JButton getBotonBuscarImagen() {
        return botonBuscarImagen;
    }
    
    public JTextField getjTextFieldImagen() {
        return jTextFieldImagen;
    }

    public Crear() {
        initComponents();
    }

    public JButton getBotonCrearV() {
        return botonCrearV;
    }

    public JButton getBotonNuevoV() {
        return botonNuevoV;
    }

    public JComboBox<String> getComboColorE() {
        return comboColorE;
    }

    public JComboBox<String> getComboColorI() {
        return comboColorI;
    }

    public JComboBox<String> getComboEstado() {
        return comboEstado;
    }

    public JComboBox<String> getComboMarcas() {
        return comboMarcas;
    }

    public JComboBox<String> getComboModelo() {
        return comboModelo;
    }

    public JFormattedTextField getJfVin() {
        return jfVin;
    }

    public JRadioButton getRadioAuto() {
        return radioAuto;
    }

    public JRadioButton getRadioManual() {
        return radioManual;
    }

    public JSpinner getSpinnerAño() {
        return spinnerAño;
    }

    public JSpinner getSpinnerKm() {
        return spinnerKm;
    }

    public JSpinner getSpinnerPrecio() {
        return spinnerPrecio;
    }

    public JTextField getTfEstilo() {
        return tfEstilo;
    }

    public JTextField getTfMotor() {
        return tfMotor;
    }

    public JTextField getTfStockNumber() {
        return tfStockNumber;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        groupTransmision = new javax.swing.ButtonGroup();
        labelStockNumber = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelMarca = new javax.swing.JLabel();
        labelModelo = new javax.swing.JLabel();
        labelEstilo = new javax.swing.JLabel();
        labelVin = new javax.swing.JLabel();
        labelColorE = new javax.swing.JLabel();
        labelColorI = new javax.swing.JLabel();
        labelKm = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelTransmision = new javax.swing.JLabel();
        labelMotor = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        spinnerKm = new javax.swing.JSpinner();
        comboMarcas = new javax.swing.JComboBox<>();
        comboColorE = new javax.swing.JComboBox<>();
        comboColorI = new javax.swing.JComboBox<>();
        comboEstado = new javax.swing.JComboBox<>();
        jfVin = new javax.swing.JFormattedTextField();
        spinnerAño = new javax.swing.JSpinner();
        spinnerPrecio = new javax.swing.JSpinner();
        radioManual = new javax.swing.JRadioButton();
        radioAuto = new javax.swing.JRadioButton();
        comboModelo = new javax.swing.JComboBox<>();
        tfStockNumber = new javax.swing.JTextField();
        tfEstilo = new javax.swing.JTextField();
        tfMotor = new javax.swing.JTextField();
        labelAño = new javax.swing.JLabel();
        botonCrearV = new javax.swing.JButton();
        botonNuevoV = new javax.swing.JButton();
        jTextFieldImagen = new javax.swing.JTextField();
        botonBuscarImagen = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        labelStockNumber.setText("Stock Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 6);
        add(labelStockNumber, gridBagConstraints);

        labelTitulo.setFont(new java.awt.Font("Source Serif Pro Semibold", 1, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Nuevo Vehículo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 6);
        add(labelTitulo, gridBagConstraints);

        labelMarca.setText("Marca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 6);
        add(labelMarca, gridBagConstraints);

        labelModelo.setText("Modelo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 24, 3, 24);
        add(labelModelo, gridBagConstraints);

        labelEstilo.setText("Estilo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 6);
        add(labelEstilo, gridBagConstraints);

        labelVin.setText("VIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 24, 3, 24);
        add(labelVin, gridBagConstraints);

        labelColorE.setText("Color exterior");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 6);
        add(labelColorE, gridBagConstraints);

        labelColorI.setText("Color interior");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 24, 3, 24);
        add(labelColorI, gridBagConstraints);

        labelKm.setText("Kilómetros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 6);
        add(labelKm, gridBagConstraints);

        labelPrecio.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 24, 3, 24);
        add(labelPrecio, gridBagConstraints);

        labelTransmision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTransmision.setText("Transmisión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 6);
        add(labelTransmision, gridBagConstraints);

        labelMotor.setText("Motor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 24, 3, 24);
        add(labelMotor, gridBagConstraints);

        labelEstado.setText("Estado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 24, 3, 24);
        add(labelEstado, gridBagConstraints);

        spinnerKm.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        add(spinnerKm, gridBagConstraints);

        comboMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acura", "Aston Martin", "Audi", "BMW", "Bentley", "Buick", "Cadillac", "Chevrolet", "Chrysler", "Dodge", "Faraday Future", "Ferrari", "Fiat", "Ford", "Genesis", "GMC", "Honda", "Hyundai", "Infinity", "Jaguar", "Jeep", "Kia", "Lamborghini", "Land Rover", "Lexus", "Lotus", "Lincoln", "MINI", "Maserati", "Mazda", "Mercedes-Benz", "Mercedes-Maybach", "Mitsubishi", "Nissan", "Pontiac", "Porsche", "Rimac Automobili", "Rolls-Royce", "Scion", "Smart", "Subaru", "Tesla", "Toyota", "Volkswagen", "Volvo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        add(comboMarcas, gridBagConstraints);

        comboColorE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        add(comboColorE, gridBagConstraints);

        comboColorI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        add(comboColorI, gridBagConstraints);

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        add(comboEstado, gridBagConstraints);

        try {
            jfVin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*****************########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        add(jfVin, gridBagConstraints);

        spinnerAño.setModel(new javax.swing.SpinnerNumberModel(1886, 1886, 2022, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        add(spinnerAño, gridBagConstraints);

        spinnerPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        add(spinnerPrecio, gridBagConstraints);

        groupTransmision.add(radioManual);
        radioManual.setText("Manual");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 6);
        add(radioManual, gridBagConstraints);

        groupTransmision.add(radioAuto);
        radioAuto.setText("Automática");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 3, 6);
        add(radioAuto, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        add(comboModelo, gridBagConstraints);

        tfStockNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfStockNumberKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        add(tfStockNumber, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        add(tfEstilo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        add(tfMotor, gridBagConstraints);

        labelAño.setText("Año");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 6, 23);
        add(labelAño, gridBagConstraints);

        botonCrearV.setText("Crear");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(botonCrearV, gridBagConstraints);

        botonNuevoV.setText("Nuevo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(botonNuevoV, gridBagConstraints);

        jTextFieldImagen.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jTextFieldImagen, gridBagConstraints);

        botonBuscarImagen.setText("Imagen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(botonBuscarImagen, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void tfStockNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStockNumberKeyTyped
        quitarNumeros(evt);
    }//GEN-LAST:event_tfStockNumberKeyTyped

    private void quitarNumeros(java.awt.event.KeyEvent evt) {
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarImagen;
    private javax.swing.JButton botonCrearV;
    private javax.swing.JButton botonNuevoV;
    private javax.swing.JComboBox<String> comboColorE;
    private javax.swing.JComboBox<String> comboColorI;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JComboBox<String> comboMarcas;
    private javax.swing.JComboBox<String> comboModelo;
    private javax.swing.ButtonGroup groupTransmision;
    private javax.swing.JTextField jTextFieldImagen;
    private javax.swing.JFormattedTextField jfVin;
    private javax.swing.JLabel labelAño;
    private javax.swing.JLabel labelColorE;
    private javax.swing.JLabel labelColorI;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelEstilo;
    private javax.swing.JLabel labelKm;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelMotor;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelStockNumber;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTransmision;
    private javax.swing.JLabel labelVin;
    private javax.swing.JRadioButton radioAuto;
    private javax.swing.JRadioButton radioManual;
    private javax.swing.JSpinner spinnerAño;
    private javax.swing.JSpinner spinnerKm;
    private javax.swing.JSpinner spinnerPrecio;
    private javax.swing.JTextField tfEstilo;
    private javax.swing.JTextField tfMotor;
    private javax.swing.JTextField tfStockNumber;
    // End of variables declaration//GEN-END:variables
}
